FROM resin/%%RESIN_MACHINE_NAME%%-debian:stretch

RUN mkdir -p /usr/src/app/
WORKDIR /usr/src/app

RUN apt-get update && apt-get install -yq --no-install-recommends \
  busybox \
  && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY ./start.sh ./

CMD ["bash", "start.sh"]
